[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mvote = "5BWRzdnfyupL8h4MpdHVgZT5bibUeLq85qrDUsu7QVmZ"

[programs.devnet]
mvote = "5BWRzdnfyupL8h4MpdHVgZT5bibUeLq85qrDUsu7QVmZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
